import { supabase, SUPABASE_PROJECT_ID, SUPABASE_URL, SUPABASE_ANON_KEY } from '../lib/supabase';
import { SensorData, MLPrediction, Alert, WorkOrder, FilterCondition, OverallStatus, HealthFactor } from '../types';

export interface SupabaseSyncStatus {
  isConnected: boolean;
  projectUrl: string;
  projectId: string;
  lastSyncTime: string | null;
  syncedRecordsCount: number;
  tablesStatus: {
    sensor_readings: boolean | null;
    filter_health: boolean | null;
    predictions: boolean | null;
    alerts: boolean | null;
    work_orders: boolean | null;
  };
  errorMessage: string | null;
  latencyMs?: number;
}

export interface SyncedSensorReadingRow {
  id?: number | string;
  equipment_id: string;
  sensor_type: string;
  value: number;
  unit: string;
  status: string;
  rate_of_change: number;
  created_at: string;
}

export interface SyncedFilterHealthRow {
  id?: number | string;
  equipment_id: string;
  health_score: number;
  condition: string;
  overall_status: string;
  factors: HealthFactor[];
  created_at: string;
}

export interface SyncedPredictionRow {
  id?: number | string;
  equipment_id: string;
  failure_probability: number;
  risk_7day: number;
  risk_30day: number;
  predicted_failure_window: string;
  model_confidence: number;
  rul_days: number;
  rul_hours: number;
  rul_confidence_lower?: number;
  rul_confidence_upper?: number;
  insights?: any;
  created_at: string;
}

export interface SyncedAlertRow {
  id: string;
  equipment_id: string;
  severity: string;
  sensor: string;
  sensor_type: string;
  value: string;
  threshold: string;
  message: string;
  recommended_action: string;
  status: string;
  acknowledged_by?: string | null;
  created_at: string;
}

export interface SyncedWorkOrderRow {
  id: string;
  equipment_id: string;
  title: string;
  priority: string;
  status: string;
  assigned_to: string;
  scheduled_date: string;
  notes?: string;
  created_at: string;
}

export const SUPABASE_SQL_SCHEMA = `-- FilterGuard AI - Complete PostgreSQL Schema for Supabase
-- Project ID: ${SUPABASE_PROJECT_ID}
-- Run this in your Supabase SQL Editor: https://supabase.com/dashboard/project/${SUPABASE_PROJECT_ID}/sql

-- 1. Sensor Readings Telemetry
CREATE TABLE IF NOT EXISTS public.sensor_readings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id TEXT NOT NULL,
  sensor_type TEXT NOT NULL,
  value NUMERIC NOT NULL,
  unit TEXT NOT NULL,
  status TEXT NOT NULL,
  rate_of_change NUMERIC DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Index for fast time-series queries
CREATE INDEX IF NOT EXISTS idx_sensor_readings_equip_time 
ON public.sensor_readings (equipment_id, created_at DESC);

-- 2. Filter Health Diagnostics
CREATE TABLE IF NOT EXISTS public.filter_health (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id TEXT NOT NULL,
  health_score INTEGER NOT NULL,
  condition TEXT NOT NULL,
  overall_status TEXT NOT NULL,
  factors JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. ML Failure Predictions & RUL
CREATE TABLE IF NOT EXISTS public.predictions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_id TEXT NOT NULL,
  failure_probability NUMERIC NOT NULL,
  risk_7day NUMERIC NOT NULL,
  risk_30day NUMERIC NOT NULL,
  predicted_failure_window TEXT NOT NULL,
  model_confidence NUMERIC NOT NULL,
  rul_days INTEGER NOT NULL,
  rul_hours INTEGER NOT NULL,
  rul_confidence_lower INTEGER,
  rul_confidence_upper INTEGER,
  insights JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Alerts & Events
CREATE TABLE IF NOT EXISTS public.alerts (
  id TEXT PRIMARY KEY,
  equipment_id TEXT NOT NULL,
  severity TEXT NOT NULL,
  sensor TEXT NOT NULL,
  sensor_type TEXT NOT NULL,
  value TEXT NOT NULL,
  threshold TEXT NOT NULL,
  message TEXT NOT NULL,
  recommended_action TEXT NOT NULL,
  status TEXT NOT NULL,
  acknowledged_by TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Maintenance Work Orders
CREATE TABLE IF NOT EXISTS public.work_orders (
  id TEXT PRIMARY KEY,
  equipment_id TEXT NOT NULL,
  title TEXT NOT NULL,
  priority TEXT NOT NULL,
  status TEXT NOT NULL,
  assigned_to TEXT NOT NULL,
  scheduled_date TEXT NOT NULL,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS) & Allow Anonymous Client Access
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.filter_health ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.predictions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.alerts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert sensor_readings') THEN
    CREATE POLICY "Allow public insert sensor_readings" ON public.sensor_readings FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert filter_health') THEN
    CREATE POLICY "Allow public insert filter_health" ON public.filter_health FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert predictions') THEN
    CREATE POLICY "Allow public insert predictions" ON public.predictions FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert alerts') THEN
    CREATE POLICY "Allow public insert alerts" ON public.alerts FOR ALL USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public insert work_orders') THEN
    CREATE POLICY "Allow public insert work_orders" ON public.work_orders FOR ALL USING (true) WITH CHECK (true);
  END IF;
END $$;
`;

// Local buffer of synced records for immediate UI inspection
class SyncedRecordStore {
  private static STORAGE_PREFIX = 'filterguard_supabase_sync_';

  static getItems<T>(table: string): T[] {
    try {
      const data = localStorage.getItem(`${this.STORAGE_PREFIX}${table}`);
      return data ? JSON.parse(data) : [];
    } catch {
      return [];
    }
  }

  static addItem<T>(table: string, item: T, maxItems = 100): void {
    try {
      const existing = this.getItems<T>(table);
      const updated = [item, ...existing].slice(0, maxItems);
      localStorage.setItem(`${this.STORAGE_PREFIX}${table}`, JSON.stringify(updated));
    } catch (e) {
      // ignore local storage quota
    }
  }

  static addBatch<T>(table: string, items: T[], maxItems = 200): void {
    try {
      const existing = this.getItems<T>(table);
      const updated = [...items, ...existing].slice(0, maxItems);
      localStorage.setItem(`${this.STORAGE_PREFIX}${table}`, JSON.stringify(updated));
    } catch (e) {
      // ignore
    }
  }
}

export class SupabaseService {
  /**
   * Measure latency & verify connection to Supabase
   */
  static async testConnection(): Promise<{
    connected: boolean;
    tables: { [key: string]: boolean };
    latencyMs: number;
    error?: string;
  }> {
    const tableStatus: { [key: string]: boolean } = {
      sensor_readings: false,
      filter_health: false,
      predictions: false,
      alerts: false,
      work_orders: false,
    };

    const startTime = performance.now();
    try {
      // Test basic connectivity via querying sensor_readings
      const { error: sensorErr } = await supabase
        .from('sensor_readings')
        .select('id')
        .limit(1);

      if (!sensorErr) {
        tableStatus.sensor_readings = true;
      }

      const { error: healthErr } = await supabase
        .from('filter_health')
        .select('id')
        .limit(1);
      if (!healthErr) tableStatus.filter_health = true;

      const { error: predErr } = await supabase
        .from('predictions')
        .select('id')
        .limit(1);
      if (!predErr) tableStatus.predictions = true;

      const { error: alertErr } = await supabase
        .from('alerts')
        .select('id')
        .limit(1);
      if (!alertErr) tableStatus.alerts = true;

      const { error: woErr } = await supabase
        .from('work_orders')
        .select('id')
        .limit(1);
      if (!woErr) tableStatus.work_orders = true;

      const latencyMs = Math.round(performance.now() - startTime);

      return {
        connected: true,
        tables: tableStatus,
        latencyMs,
      };
    } catch (err: any) {
      const latencyMs = Math.round(performance.now() - startTime);
      return {
        connected: false,
        tables: tableStatus,
        latencyMs,
        error: err.message || 'Connection to Supabase failed',
      };
    }
  }

  /**
   * Save sensor readings to Supabase
   */
  static async saveSensorReadings(equipmentId: string, sensors: SensorData[]) {
    const records: SyncedSensorReadingRow[] = sensors
      .filter(s => s.isAvailable)
      .map(s => ({
        equipment_id: equipmentId,
        sensor_type: s.type,
        value: s.value,
        unit: s.unit,
        status: s.status,
        rate_of_change: s.rateOfChange,
        created_at: new Date().toISOString(),
      }));

    // Save into local record store for instant inspection in UI
    SyncedRecordStore.addBatch('sensor_readings', records);

    try {
      const { data, error } = await supabase
        .from('sensor_readings')
        .insert(records);

      if (error) throw error;
      return { success: true, count: records.length, data };
    } catch (err: any) {
      console.warn('Supabase: recorded locally (create tables in Supabase SQL editor):', err.message);
      return { success: true, count: records.length, localFallback: true, error: err.message };
    }
  }

  /**
   * Save filter health state to Supabase
   */
  static async saveFilterHealth(
    equipmentId: string,
    healthScore: number,
    condition: FilterCondition,
    overallStatus: OverallStatus,
    factors: HealthFactor[]
  ) {
    const row: SyncedFilterHealthRow = {
      equipment_id: equipmentId,
      health_score: healthScore,
      condition,
      overall_status: overallStatus,
      factors,
      created_at: new Date().toISOString(),
    };

    SyncedRecordStore.addItem('filter_health', row);

    try {
      const { data, error } = await supabase
        .from('filter_health')
        .insert(row);

      if (error) throw error;
      return { success: true, data };
    } catch (err: any) {
      return { success: true, localFallback: true, error: err.message };
    }
  }

  /**
   * Save ML Prognostics and RUL prediction to Supabase
   */
  static async savePrediction(equipmentId: string, prediction: MLPrediction) {
    const row: SyncedPredictionRow = {
      equipment_id: equipmentId,
      failure_probability: prediction.failureProbability,
      risk_7day: prediction.risk7Day,
      risk_30day: prediction.risk30Day,
      predicted_failure_window: prediction.predictedFailureWindow,
      model_confidence: prediction.modelConfidence,
      rul_days: prediction.rulDays,
      rul_hours: prediction.rulHours,
      rul_confidence_lower: prediction.rulConfidenceInterval[0],
      rul_confidence_upper: prediction.rulConfidenceInterval[1],
      insights: prediction.insights,
      created_at: new Date().toISOString(),
    };

    SyncedRecordStore.addItem('predictions', row);

    try {
      const { data, error } = await supabase
        .from('predictions')
        .insert(row);

      if (error) throw error;
      return { success: true, data };
    } catch (err: any) {
      return { success: true, localFallback: true, error: err.message };
    }
  }

  /**
   * Upsert alert into Supabase
   */
  static async syncAlert(equipmentId: string, alert: Alert) {
    const row: SyncedAlertRow = {
      id: alert.id,
      equipment_id: equipmentId,
      severity: alert.severity,
      sensor: alert.sensor,
      sensor_type: alert.sensorType,
      value: String(alert.value),
      threshold: String(alert.threshold),
      message: alert.message,
      recommended_action: alert.recommendedAction,
      status: alert.status,
      acknowledged_by: alert.acknowledgedBy || null,
      created_at: new Date().toISOString(),
    };

    SyncedRecordStore.addItem('alerts', row);

    try {
      const { data, error } = await supabase
        .from('alerts')
        .upsert(row);

      if (error) throw error;
      return { success: true, data };
    } catch (err: any) {
      return { success: true, localFallback: true, error: err.message };
    }
  }

  /**
   * Upsert work order into Supabase
   */
  static async syncWorkOrder(equipmentId: string, wo: WorkOrder) {
    const row: SyncedWorkOrderRow = {
      id: wo.id,
      equipment_id: equipmentId,
      title: wo.title,
      priority: wo.priority,
      status: wo.status,
      assigned_to: wo.assignedTo,
      scheduled_date: wo.scheduledDate,
      notes: wo.notes,
      created_at: new Date().toISOString(),
    };

    SyncedRecordStore.addItem('work_orders', row);

    try {
      const { data, error } = await supabase
        .from('work_orders')
        .upsert(row);

      if (error) throw error;
      return { success: true, data };
    } catch (err: any) {
      return { success: true, localFallback: true, error: err.message };
    }
  }

  /**
   * Fetch recent readings from Supabase (or fallback to local buffer)
   */
  static async fetchRecentReadings(equipmentId: string, limit = 50): Promise<SyncedSensorReadingRow[]> {
    try {
      const { data, error } = await supabase
        .from('sensor_readings')
        .select('*')
        .eq('equipment_id', equipmentId)
        .order('created_at', { ascending: false })
        .limit(limit);

      if (error || !data || data.length === 0) {
        return SyncedRecordStore.getItems<SyncedSensorReadingRow>('sensor_readings');
      }
      return data;
    } catch {
      return SyncedRecordStore.getItems<SyncedSensorReadingRow>('sensor_readings');
    }
  }

  /**
   * Fetch filter health records from Supabase
   */
  static async fetchRecentHealth(equipmentId: string, limit = 20): Promise<SyncedFilterHealthRow[]> {
    try {
      const { data, error } = await supabase
        .from('filter_health')
        .select('*')
        .eq('equipment_id', equipmentId)
        .order('created_at', { ascending: false })
        .limit(limit);

      if (error || !data || data.length === 0) {
        return SyncedRecordStore.getItems<SyncedFilterHealthRow>('filter_health');
      }
      return data;
    } catch {
      return SyncedRecordStore.getItems<SyncedFilterHealthRow>('filter_health');
    }
  }

  /**
   * Fetch predictions from Supabase
   */
  static async fetchRecentPredictions(equipmentId: string, limit = 20): Promise<SyncedPredictionRow[]> {
    try {
      const { data, error } = await supabase
        .from('predictions')
        .select('*')
        .eq('equipment_id', equipmentId)
        .order('created_at', { ascending: false })
        .limit(limit);

      if (error || !data || data.length === 0) {
        return SyncedRecordStore.getItems<SyncedPredictionRow>('predictions');
      }
      return data;
    } catch {
      return SyncedRecordStore.getItems<SyncedPredictionRow>('predictions');
    }
  }

  /**
   * Fetch alerts from Supabase
   */
  static async fetchRecentAlerts(equipmentId: string, limit = 20): Promise<SyncedAlertRow[]> {
    try {
      const { data, error } = await supabase
        .from('alerts')
        .select('*')
        .eq('equipment_id', equipmentId)
        .order('created_at', { ascending: false })
        .limit(limit);

      if (error || !data || data.length === 0) {
        return SyncedRecordStore.getItems<SyncedAlertRow>('alerts');
      }
      return data;
    } catch {
      return SyncedRecordStore.getItems<SyncedAlertRow>('alerts');
    }
  }

  /**
   * Fetch work orders from Supabase
   */
  static async fetchRecentWorkOrders(equipmentId: string, limit = 20): Promise<SyncedWorkOrderRow[]> {
    try {
      const { data, error } = await supabase
        .from('work_orders')
        .select('*')
        .eq('equipment_id', equipmentId)
        .order('created_at', { ascending: false })
        .limit(limit);

      if (error || !data || data.length === 0) {
        return SyncedRecordStore.getItems<SyncedWorkOrderRow>('work_orders');
      }
      return data;
    } catch {
      return SyncedRecordStore.getItems<SyncedWorkOrderRow>('work_orders');
    }
  }

  /**
   * Local store accessor
   */
  static getLocalBuffer<T>(table: string): T[] {
    return SyncedRecordStore.getItems<T>(table);
  }
}
